fname: Scheduled and Manual Python Script

on:
  schedule:
    - cron: '0 0 * * 0'  # 每周日凌晨 12:00 运行（UTC 时间）
  workflow_dispatch:  # 允许手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run Python script
        run: python name: Scheduled and Manual Python Script

on:
  schedule:
    - cron: '0 6 * * 0'  # 每周日凌晨 12:00 运行（UTC 时间）
  workflow_dispatch:  # 允许手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run Python script
        run: python fetch_stream.py  # 请替换为你的 Python 脚本名  # 请替换为你的 Python 脚本名

    - name: Commit live URL
      run: |
        git config --local user.email "315723172@qq.com"
        git config --local user.name "GitHub Action"
        git add live_url.txt
        git commit -m "Update live URL"
        git push
