name: update-lives-list

on:
  schedule:
    - cron: '0 20 * * *'
  push:
    branches:
      - main
    paths:
      - 'fetch_streams.py'  # 仅当 fetch_streams.py 文件被修改时触发
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
      
        run:  
             pip install selenium requests futures eventlet beautifulsoup4
      - name: Run fetch_stream
        run: python ${{ github.workspace }}/fetch_streams.py

        
      - name: 提交
        run: |
          git config --global user.email "315723172@qq.com"
          git config --global user.name "jjjay001"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/jjjay001/sy-iptv.git
          git add .
          git commit -m "ShaanxiTV.m3u文件" || echo "No changes to commit"
          git push origin main
          exit 0
