name: update-lives-list

on:
  schedule:
    - cron: '0 6 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
      
        run:  
             pip install selenium requests futures eventlet

      - name: Run fetch_stream
        run: python ${{ github.workspace }}/fetch_stream.py

        
      - name: 提交
        run: |
          git config --global user.email "315723172@qq.com"
          git config --global user.name "jjjay001"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/jjjay001/sy-iptv.git
          git add .
          git commit *.txt -m "Add generated file"
          git commit *.m3u -m "Add generated file"
          #git pull --rebase
          git push -f
